name: Deploy to Vercel

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
